### ISSUE TITLE
Update for OBS 28.0.1

### ISSUE THREAD

**Issue by kibisilicate** [dougg3/obs-ios-camera-source#14]
OBS 28.0.1 was released arround a month ago and the upstream of this plugin was updated to support it.

I tried to compile the upstream version in a debian chroot but it failed.

```
$ cmake .. -DLIBOBS_INCLUDE_DIR=/Projects/obs-studio/cmake
CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Projects/obs-ios-camera-source/build/CMakeFiles/CMakeOutput.log".
```

I'm not skilled enough to get it compiled and working on my own.

Is this fork of the plugin going to get updated soon or should I try running the windown version of OBS and the plugin in wine instead?

**Comment by dougg3** [comment]
Hi there,

As far as I can tell, the current plugin source code (at this repo) is still compatible with OBS 28 -- I just tested it and it still works fine. I do need to update it with the latest upstream changes, but it should still work as is. I did run into some problems building it on Ubuntu 22.04 though -- it gives the same error you shared above. I will look into that when I get a chance, but in the meantime, here's what I had to change in the README's build instructions to get it to work as a temporary fix:

- Remove the line `find_package(LibObs REQUIRED)` in CMakeLists.txt
- Under `target_link_libraries(obs-ios-camera-source` in CMakeLists.txt, change `libobs` to `obs`
- Use this cmake command instead of what the instructions say: `cmake .. -DLIBOBS_INCLUDE_DIR=~/Downloads/obs-studio/cmake -DCMAKE_CXX_FLAGS=-I${HOME}/Downloads/obs-studio/libobs -DCMAKE_C_FLAGS=-I${HOME}/Downloads/obs-studio/libobs`

Hope this helps! Sounds like I need to fix the libobs detection.
